spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=spring"
    username: "postgres"
    password: "kinder8156946"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: "org.hibernate.dialect.PostgreSQLDialect"

health: true
solid: true
dry: true
tdd: true

custom:
  included: true